<h3>Se connecter avec un compte utilisateur</h3>

<form action="index.php?action=connexion" method="post">
    <fieldset>
        <legend>Informations d'authentification</legend>
        <label for="">E-mail *</label>
        <input type="email" name="mail" id="mail" value="" required/><br>
        <label for="">Mot de passe *</label>
        <input type="password" name="mdp" id="mdp" value="" required/>
    </fieldset>
        
    <div class="bouton">
    <button type="submit" class="submit" id="bouton">Se connecter</button>
    <button type="reset" class="submit">Annuler</a></button>
    </div>
</form>

<script type="module" src="views/js/script2.js"></script>