
<form action="index.php?action=createAccount" method="post">
    <fieldset class="connexion">
        <legend>Identité et coordonnées</legend>
        
        <!--<div class="pseudo_admin">-->
        <label for="">Nom * </label>
        <input type="text" name="nom" id="nom" value="" required/><br>
        <label for="">Prénom * </label>
        <input type="text" name="prenom" id="prenom" value="" required/><br>
        <label for="">Date de naissance * </label>
        <input type="date" name="anniversaire" id="anniversaire" value="" required/><br>
        <label for="">Adresse * </label>
        <input type="text" name="adresse" id="adresse"value="" required/><br>
        <!--<textarea id="story" name="adresse" id="adresse" rows="4" cols="20" value=""></textarea><br>-->
        <label for="">Code postal et ville * </label>
        <input type="text" name="codePostal" id="codePostal" value="" required/><br>
        <label for="">Pays *</label>
        <input type="text" name="pays" id="pays" value="" required/><br>
        <label for="">Téléphone: </label>
        <input type="phone" name="tel" id="tel" value="" required/><br>
    </fieldset>   
        
    <fieldset>
        <legend>Informations d'authentification</legend>
        <label for="">E-mail *</label>
        <input type="email" name="mail" id="mail" value="" required/><br>
        <label for="">Mot de passe *</label>
        <input type="password" name="mdp" id="mdp" value="" required/>
    </fieldset>
        
    <div class="bouton">
    <button type="submit" class="submit" id="bouton">Créer un compte</button>
    <button type="reset" class="submit"><a href="admin2.php">Annuler</a></button>
    </div>
</form>
<script type="module" src="views/js/script.js"></script>