<?php if(array_key_exists('id',$_GET)) : ?>
<form method="POST" action="index.php?action=modifyProfile">
  <label for="nom">Nom :</label>
  <input type="text" id="nom" name="nom" value="<?= $user['nom'] ?>" required><br>
  
  <label for="prenom">Prénom :</label>
  <input type="text" id="prenom" name="prenom" value="<?= $user['prenom'] ?>" required><br>

  <label for="date_de_naissance">Date de naissance :</label>
  <input type="date" id="date_de_naissance" name="anniversaire" value="<?= $user['anniversaire'] ?>" required><br>

  <label for="adresse">Adresse :</label>
  <input type="text" id="adresse" name="adresse" value="<?= $user['adresse'] ?>" required><br>

  <label for="pays">Pays :</label>
  <input type="text" id="pays" name="pays" value="<?= $user['pays'] ?>" required><br>

  <label for="code_postal">Code postal :</label>
  <input type="text" id="code_postal" name="codePostal" value="<?= $user['code_postal'] ?>" required><br>
  
  <label for="telephone">Téléphone :</label>
  <input type="tel" id="telephone" name="tel" value="<?= $user['tel'] ?>" required><br>

  <label for="email">Email :</label>
  <input type="email" id="email" name="mail" value="<?= $user['mail'] ?>" required><br>

  <input type="submit" value="Enregistrer les modifications">
</form>

<?php endif ?>